// Auto-generated by Payload when custom admin components are registered.
// Regenerate with `payload generate:importmap` after adding any. Starts
// empty because this scaffold uses no custom admin UI components yet.
export const importMap = {};
